import { useEffect, useRef, useState } from "react";
import mermaid from "mermaid";

let _id = 0;

/**
 * Renders a Mermaid diagram from a chart definition string.
 * The SVG output is generated by the mermaid library from a hardcoded chart
 * string defined in source code — not from user input — so XSS risk is minimal.
 */
export function MermaidDiagram({ chart }: { chart: string }) {
  const [svg, setSvg] = useState("");
  const idRef = useRef(`mermaid-${++_id}`);

  useEffect(() => {
    mermaid.initialize({
      startOnLoad: false,
      theme: "neutral",
      securityLevel: "loose",
    });
    mermaid
      .render(idRef.current, chart)
      .then(({ svg }) => setSvg(svg))
      .catch(console.error);
  }, [chart]);

  // eslint-disable-next-line react/no-danger -- SVG from mermaid library, not user input
  return (
    <div
      className="flex justify-center overflow-x-auto [&_svg]:max-w-full"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
