/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SubmissionsIndexRouteImport } from "./routes/submissions.index"
import { Route as SubmissionsIdRouteImport } from "./routes/submissions.$id"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIndexRoute = SubmissionsIndexRouteImport.update({
  id: "/submissions/",
  path: "/submissions/",
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIdRoute = SubmissionsIdRouteImport.update({
  id: "/submissions/$id",
  path: "/submissions/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/submissions/$id": typeof SubmissionsIdRoute
  "/submissions/": typeof SubmissionsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/submissions/$id": typeof SubmissionsIdRoute
  "/submissions": typeof SubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/login": typeof LoginRoute
  "/settings": typeof SettingsRoute
  "/submissions/$id": typeof SubmissionsIdRoute
  "/submissions/": typeof SubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/login" | "/settings" | "/submissions/$id" | "/submissions/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/login" | "/settings" | "/submissions/$id" | "/submissions"
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/settings"
    | "/submissions/$id"
    | "/submissions/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SubmissionsIdRoute: typeof SubmissionsIdRoute
  SubmissionsIndexRoute: typeof SubmissionsIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/submissions/": {
      id: "/submissions/"
      path: "/submissions"
      fullPath: "/submissions/"
      preLoaderRoute: typeof SubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/submissions/$id": {
      id: "/submissions/$id"
      path: "/submissions/$id"
      fullPath: "/submissions/$id"
      preLoaderRoute: typeof SubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SubmissionsIdRoute: SubmissionsIdRoute,
  SubmissionsIndexRoute: SubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
